version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: instagtest
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
     build: manage/
     container_name: application
     command: python ./manage.py
     ports:
       - 1234:1234
     environment:
       POSTGRES_HOST: db
     restart: always
     links:
       - db